# https://snarky.ca/what-the-heck-is-pyproject-toml/

[build-system]
requires = [
    "setuptools",
    "wheel",
]

[tool.black]
# https://github.com/psf/black
line-length = 80
target-version = ["py36"]
exclude = "(.eggs|.git|.hg|.mypy_cache|.venv|_build|build|dist)"
